//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card_details()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int card_no { get; set; }
        public string name_on_card { get; set; }
        public int cvc_no { get; set; }
        public int pin { get; set; }
        public int account_no { get; set; }
        public System.DateTime exp_date { get; set; }
        public string Bank_id { get; set; }
        public string card_type { get; set; }
    
        public virtual Bank_details Bank_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
