//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Hotel_Reservation_SystemEntities : DbContext
    {
        public Hotel_Reservation_SystemEntities()
            : base("name=Hotel_Reservation_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank_details> Bank_details { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Card_details> Card_details { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PinCode> PinCodes { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
    
        public virtual int Delete_booking(string booking_id)
        {
            var booking_idParameter = booking_id != null ?
                new ObjectParameter("Booking_id", booking_id) :
                new ObjectParameter("Booking_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_booking", booking_idParameter);
        }
    
        public virtual int Delete_customer(string customer_id)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("Customer_id", customer_id) :
                new ObjectParameter("Customer_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_customer", customer_idParameter);
        }
    
        public virtual int Delete_hotel(string hotel_id)
        {
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("Hotel_id", hotel_id) :
                new ObjectParameter("Hotel_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_hotel", hotel_idParameter);
        }
    
        public virtual int Delete_manager(string manager_id)
        {
            var manager_idParameter = manager_id != null ?
                new ObjectParameter("Manager_id", manager_id) :
                new ObjectParameter("Manager_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_manager", manager_idParameter);
        }
    
        public virtual int Delete_payment(string payment_id)
        {
            var payment_idParameter = payment_id != null ?
                new ObjectParameter("Payment_id", payment_id) :
                new ObjectParameter("Payment_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_payment", payment_idParameter);
        }
    
        public virtual int GetBookingDetails(string booking_id, ObjectParameter hotel_id, ObjectParameter booking_Date, ObjectParameter arrival_Date, ObjectParameter departure_Date, ObjectParameter number_of_Adults, ObjectParameter number_of_Children, ObjectParameter number_of_Nights, ObjectParameter number_of_AC_Rooms, ObjectParameter number_of_Non_AC_Rooms)
        {
            var booking_idParameter = booking_id != null ?
                new ObjectParameter("Booking_id", booking_id) :
                new ObjectParameter("Booking_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetBookingDetails", booking_idParameter, hotel_id, booking_Date, arrival_Date, departure_Date, number_of_Adults, number_of_Children, number_of_Nights, number_of_AC_Rooms, number_of_Non_AC_Rooms);
        }
    
        public virtual ObjectResult<string> GetCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCities");
        }
    
        public virtual ObjectResult<GetCitiesStates_Result> GetCitiesStates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCitiesStates_Result>("GetCitiesStates");
        }
    
        public virtual int GetCustomerDetails(string customer_id, ObjectParameter name, ObjectParameter c_contact, ObjectParameter c_email, ObjectParameter dob, ObjectParameter pincode, ObjectParameter state, ObjectParameter city, ObjectParameter password)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCustomerDetails", customer_idParameter, name, c_contact, c_email, dob, pincode, state, city, password);
        }
    
        public virtual int GetHotelDetails(string hotel_id, ObjectParameter name, ObjectParameter hotel_description, ObjectParameter pincode, ObjectParameter state, ObjectParameter city, ObjectParameter manager_id, ObjectParameter ac_room, ObjectParameter non_ac_room)
        {
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("hotel_id", hotel_id) :
                new ObjectParameter("hotel_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetHotelDetails", hotel_idParameter, name, hotel_description, pincode, state, city, manager_id, ac_room, non_ac_room);
        }
    
        public virtual int GetManagerDetails(string manager_id, ObjectParameter name, ObjectParameter password, ObjectParameter m_contact, ObjectParameter m_email)
        {
            var manager_idParameter = manager_id != null ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetManagerDetails", manager_idParameter, name, password, m_contact, m_email);
        }
    
        public virtual ObjectResult<GetManagerHotels_Result> GetManagerHotels(string manager_id)
        {
            var manager_idParameter = manager_id != null ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManagerHotels_Result>("GetManagerHotels", manager_idParameter);
        }
    
        public virtual ObjectResult<string> GetStates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetStates");
        }
    
        public virtual ObjectResult<hotel_room_avilablity_Result> hotel_room_avilablity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hotel_room_avilablity_Result>("hotel_room_avilablity");
        }
    
        public virtual ObjectResult<hotel_room_avilablity_CCIO_Result> hotel_room_avilablity_CCIO(string state, string city, Nullable<System.DateTime> indate, Nullable<System.DateTime> outdate)
        {
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var indateParameter = indate.HasValue ?
                new ObjectParameter("indate", indate) :
                new ObjectParameter("indate", typeof(System.DateTime));
    
            var outdateParameter = outdate.HasValue ?
                new ObjectParameter("outdate", outdate) :
                new ObjectParameter("outdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hotel_room_avilablity_CCIO_Result>("hotel_room_avilablity_CCIO", stateParameter, cityParameter, indateParameter, outdateParameter);
        }
    
        public virtual int InBooking(ObjectParameter booking_id, string customer_id, string hotel_id, Nullable<int> no_Of_AC_Rooms, Nullable<int> no_Of_Non_AC_Rooms, string t_id, Nullable<System.DateTime> date_booking, Nullable<System.DateTime> date_checkin, Nullable<System.DateTime> date_checkout, Nullable<int> no_adult, Nullable<int> no_child)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("Customer_id", customer_id) :
                new ObjectParameter("Customer_id", typeof(string));
    
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("Hotel_id", hotel_id) :
                new ObjectParameter("Hotel_id", typeof(string));
    
            var no_Of_AC_RoomsParameter = no_Of_AC_Rooms.HasValue ?
                new ObjectParameter("No_Of_AC_Rooms", no_Of_AC_Rooms) :
                new ObjectParameter("No_Of_AC_Rooms", typeof(int));
    
            var no_Of_Non_AC_RoomsParameter = no_Of_Non_AC_Rooms.HasValue ?
                new ObjectParameter("No_Of_Non_AC_Rooms", no_Of_Non_AC_Rooms) :
                new ObjectParameter("No_Of_Non_AC_Rooms", typeof(int));
    
            var t_idParameter = t_id != null ?
                new ObjectParameter("T_id", t_id) :
                new ObjectParameter("T_id", typeof(string));
    
            var date_bookingParameter = date_booking.HasValue ?
                new ObjectParameter("Date_booking", date_booking) :
                new ObjectParameter("Date_booking", typeof(System.DateTime));
    
            var date_checkinParameter = date_checkin.HasValue ?
                new ObjectParameter("Date_checkin", date_checkin) :
                new ObjectParameter("Date_checkin", typeof(System.DateTime));
    
            var date_checkoutParameter = date_checkout.HasValue ?
                new ObjectParameter("Date_checkout", date_checkout) :
                new ObjectParameter("Date_checkout", typeof(System.DateTime));
    
            var no_adultParameter = no_adult.HasValue ?
                new ObjectParameter("no_adult", no_adult) :
                new ObjectParameter("no_adult", typeof(int));
    
            var no_childParameter = no_child.HasValue ?
                new ObjectParameter("no_child", no_child) :
                new ObjectParameter("no_child", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InBooking", booking_id, customer_idParameter, hotel_idParameter, no_Of_AC_RoomsParameter, no_Of_Non_AC_RoomsParameter, t_idParameter, date_bookingParameter, date_checkinParameter, date_checkoutParameter, no_adultParameter, no_childParameter);
        }
    
        public virtual int InCustomerDetails(ObjectParameter customer_id, string c_name, Nullable<long> c_contact, string c_email, Nullable<System.DateTime> dob, Nullable<int> pin, string state, string city, string password)
        {
            var c_nameParameter = c_name != null ?
                new ObjectParameter("c_name", c_name) :
                new ObjectParameter("c_name", typeof(string));
    
            var c_contactParameter = c_contact.HasValue ?
                new ObjectParameter("c_contact", c_contact) :
                new ObjectParameter("c_contact", typeof(long));
    
            var c_emailParameter = c_email != null ?
                new ObjectParameter("c_email", c_email) :
                new ObjectParameter("c_email", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InCustomerDetails", customer_id, c_nameParameter, c_contactParameter, c_emailParameter, dobParameter, pinParameter, stateParameter, cityParameter, passwordParameter);
        }
    
        public virtual int InHotel(ObjectParameter hotel_id, string name, string hotel_description, Nullable<int> pincode, string state, string city, string manager_id, Nullable<int> ac_room, Nullable<int> non_ac_room)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var hotel_descriptionParameter = hotel_description != null ?
                new ObjectParameter("hotel_description", hotel_description) :
                new ObjectParameter("hotel_description", typeof(string));
    
            var pincodeParameter = pincode.HasValue ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var manager_idParameter = manager_id != null ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(string));
    
            var ac_roomParameter = ac_room.HasValue ?
                new ObjectParameter("ac_room", ac_room) :
                new ObjectParameter("ac_room", typeof(int));
    
            var non_ac_roomParameter = non_ac_room.HasValue ?
                new ObjectParameter("non_ac_room", non_ac_room) :
                new ObjectParameter("non_ac_room", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InHotel", hotel_id, nameParameter, hotel_descriptionParameter, pincodeParameter, stateParameter, cityParameter, manager_idParameter, ac_roomParameter, non_ac_roomParameter);
        }
    
        public virtual int InManagerDetails(ObjectParameter manager_id, string m_name, string m_password, Nullable<long> m_contact, string m_email)
        {
            var m_nameParameter = m_name != null ?
                new ObjectParameter("m_name", m_name) :
                new ObjectParameter("m_name", typeof(string));
    
            var m_passwordParameter = m_password != null ?
                new ObjectParameter("m_password", m_password) :
                new ObjectParameter("m_password", typeof(string));
    
            var m_contactParameter = m_contact.HasValue ?
                new ObjectParameter("m_contact", m_contact) :
                new ObjectParameter("m_contact", typeof(long));
    
            var m_emailParameter = m_email != null ?
                new ObjectParameter("m_email", m_email) :
                new ObjectParameter("m_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InManagerDetails", manager_id, m_nameParameter, m_passwordParameter, m_contactParameter, m_emailParameter);
        }
    
        public virtual int InPin(Nullable<int> pin, string state, string city)
        {
            var pinParameter = pin.HasValue ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InPin", pinParameter, stateParameter, cityParameter);
        }
    
        public virtual int InRoom(string hotel_id, Nullable<int> room_No, string room_type, Nullable<int> price_adult, Nullable<int> price_child)
        {
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("hotel_id", hotel_id) :
                new ObjectParameter("hotel_id", typeof(string));
    
            var room_NoParameter = room_No.HasValue ?
                new ObjectParameter("room_No", room_No) :
                new ObjectParameter("room_No", typeof(int));
    
            var room_typeParameter = room_type != null ?
                new ObjectParameter("room_type", room_type) :
                new ObjectParameter("room_type", typeof(string));
    
            var price_adultParameter = price_adult.HasValue ?
                new ObjectParameter("price_adult", price_adult) :
                new ObjectParameter("price_adult", typeof(int));
    
            var price_childParameter = price_child.HasValue ?
                new ObjectParameter("price_child", price_child) :
                new ObjectParameter("price_child", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InRoom", hotel_idParameter, room_NoParameter, room_typeParameter, price_adultParameter, price_childParameter);
        }
    
        public virtual int Price(string hotel_id, ObjectParameter price_adult_ac_room, ObjectParameter price_child_ac_room, ObjectParameter price_adult_non_ac_room, ObjectParameter price_child_non_ac_room)
        {
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("hotel_id", hotel_id) :
                new ObjectParameter("hotel_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Price", hotel_idParameter, price_adult_ac_room, price_child_ac_room, price_adult_non_ac_room, price_child_non_ac_room);
        }
    
        public virtual int sp_customer_login(string username, string password, ObjectParameter customerstatus)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_customer_login", usernameParameter, passwordParameter, customerstatus);
        }
    
        public virtual int sp_Managers_login(string username, string password, ObjectParameter managersstatus)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Managers_login", usernameParameter, passwordParameter, managersstatus);
        }
    
        public virtual int sp_payment(string bank_Id, Nullable<long> creditCardNo, string cardtype, string nameOnCard, Nullable<System.DateTime> expiryDate, Nullable<int> cVV, Nullable<long> accountNumber, Nullable<int> pin, ObjectParameter paystatus)
        {
            var bank_IdParameter = bank_Id != null ?
                new ObjectParameter("Bank_Id", bank_Id) :
                new ObjectParameter("Bank_Id", typeof(string));
    
            var creditCardNoParameter = creditCardNo.HasValue ?
                new ObjectParameter("CreditCardNo", creditCardNo) :
                new ObjectParameter("CreditCardNo", typeof(long));
    
            var cardtypeParameter = cardtype != null ?
                new ObjectParameter("Cardtype", cardtype) :
                new ObjectParameter("Cardtype", typeof(string));
    
            var nameOnCardParameter = nameOnCard != null ?
                new ObjectParameter("NameOnCard", nameOnCard) :
                new ObjectParameter("NameOnCard", typeof(string));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var cVVParameter = cVV.HasValue ?
                new ObjectParameter("CVV", cVV) :
                new ObjectParameter("CVV", typeof(int));
    
            var accountNumberParameter = accountNumber.HasValue ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(long));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("Pin", pin) :
                new ObjectParameter("Pin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_payment", bank_IdParameter, creditCardNoParameter, cardtypeParameter, nameOnCardParameter, expiryDateParameter, cVVParameter, accountNumberParameter, pinParameter, paystatus);
        }
    
        public virtual int sp_store_payment(ObjectParameter payment_id, string hotel_id, string customer_Id, string booking_name, Nullable<int> total_Cost, Nullable<int> card_number, string card_type)
        {
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("Hotel_id", hotel_id) :
                new ObjectParameter("Hotel_id", typeof(string));
    
            var customer_IdParameter = customer_Id != null ?
                new ObjectParameter("customer_Id", customer_Id) :
                new ObjectParameter("customer_Id", typeof(string));
    
            var booking_nameParameter = booking_name != null ?
                new ObjectParameter("booking_name", booking_name) :
                new ObjectParameter("booking_name", typeof(string));
    
            var total_CostParameter = total_Cost.HasValue ?
                new ObjectParameter("total_Cost", total_Cost) :
                new ObjectParameter("total_Cost", typeof(int));
    
            var card_numberParameter = card_number.HasValue ?
                new ObjectParameter("card_number", card_number) :
                new ObjectParameter("card_number", typeof(int));
    
            var card_typeParameter = card_type != null ?
                new ObjectParameter("card_type", card_type) :
                new ObjectParameter("card_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_store_payment", payment_id, hotel_idParameter, customer_IdParameter, booking_nameParameter, total_CostParameter, card_numberParameter, card_typeParameter);
        }
    
        public virtual int UpdateBookingDetails(string booking_id, Nullable<int> no_Of_Ac_Rooms, Nullable<int> no_Of_Non_Ac_Rooms, Nullable<System.DateTime> date_Of_ChekInn, Nullable<System.DateTime> date_Of_CheckOut, Nullable<int> no_Of_Adults, Nullable<int> no_Of_Children)
        {
            var booking_idParameter = booking_id != null ?
                new ObjectParameter("Booking_id", booking_id) :
                new ObjectParameter("Booking_id", typeof(string));
    
            var no_Of_Ac_RoomsParameter = no_Of_Ac_Rooms.HasValue ?
                new ObjectParameter("No_Of_Ac_Rooms", no_Of_Ac_Rooms) :
                new ObjectParameter("No_Of_Ac_Rooms", typeof(int));
    
            var no_Of_Non_Ac_RoomsParameter = no_Of_Non_Ac_Rooms.HasValue ?
                new ObjectParameter("No_Of_Non_Ac_Rooms", no_Of_Non_Ac_Rooms) :
                new ObjectParameter("No_Of_Non_Ac_Rooms", typeof(int));
    
            var date_Of_ChekInnParameter = date_Of_ChekInn.HasValue ?
                new ObjectParameter("Date_Of_ChekInn", date_Of_ChekInn) :
                new ObjectParameter("Date_Of_ChekInn", typeof(System.DateTime));
    
            var date_Of_CheckOutParameter = date_Of_CheckOut.HasValue ?
                new ObjectParameter("Date_Of_CheckOut", date_Of_CheckOut) :
                new ObjectParameter("Date_Of_CheckOut", typeof(System.DateTime));
    
            var no_Of_AdultsParameter = no_Of_Adults.HasValue ?
                new ObjectParameter("No_Of_Adults", no_Of_Adults) :
                new ObjectParameter("No_Of_Adults", typeof(int));
    
            var no_Of_ChildrenParameter = no_Of_Children.HasValue ?
                new ObjectParameter("No_Of_Children", no_Of_Children) :
                new ObjectParameter("No_Of_Children", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBookingDetails", booking_idParameter, no_Of_Ac_RoomsParameter, no_Of_Non_Ac_RoomsParameter, date_Of_ChekInnParameter, date_Of_CheckOutParameter, no_Of_AdultsParameter, no_Of_ChildrenParameter);
        }
    
        public virtual int UpdateCustomerDetails(string customer_id, string name, Nullable<long> c_contact, string c_email, Nullable<System.DateTime> dob, Nullable<int> pin, string state, string city, string password)
        {
            var customer_idParameter = customer_id != null ?
                new ObjectParameter("Customer_id", customer_id) :
                new ObjectParameter("Customer_id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var c_contactParameter = c_contact.HasValue ?
                new ObjectParameter("c_contact", c_contact) :
                new ObjectParameter("c_contact", typeof(long));
    
            var c_emailParameter = c_email != null ?
                new ObjectParameter("c_email", c_email) :
                new ObjectParameter("c_email", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("Dob", dob) :
                new ObjectParameter("Dob", typeof(System.DateTime));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCustomerDetails", customer_idParameter, nameParameter, c_contactParameter, c_emailParameter, dobParameter, pinParameter, stateParameter, cityParameter, passwordParameter);
        }
    
        public virtual int UpdateHotel(string hotel_id, string name, string hotel_description, Nullable<int> pin, string state, string city, string manager_id, Nullable<int> ac_room, Nullable<int> non_ac_room, Nullable<int> price_adult_ac, Nullable<int> price_adult_nonac, Nullable<int> price_child_ac, Nullable<int> price_child_nonac)
        {
            var hotel_idParameter = hotel_id != null ?
                new ObjectParameter("hotel_id", hotel_id) :
                new ObjectParameter("hotel_id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var hotel_descriptionParameter = hotel_description != null ?
                new ObjectParameter("hotel_description", hotel_description) :
                new ObjectParameter("hotel_description", typeof(string));
    
            var pinParameter = pin.HasValue ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var manager_idParameter = manager_id != null ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(string));
    
            var ac_roomParameter = ac_room.HasValue ?
                new ObjectParameter("ac_room", ac_room) :
                new ObjectParameter("ac_room", typeof(int));
    
            var non_ac_roomParameter = non_ac_room.HasValue ?
                new ObjectParameter("non_ac_room", non_ac_room) :
                new ObjectParameter("non_ac_room", typeof(int));
    
            var price_adult_acParameter = price_adult_ac.HasValue ?
                new ObjectParameter("price_adult_ac", price_adult_ac) :
                new ObjectParameter("price_adult_ac", typeof(int));
    
            var price_adult_nonacParameter = price_adult_nonac.HasValue ?
                new ObjectParameter("price_adult_nonac", price_adult_nonac) :
                new ObjectParameter("price_adult_nonac", typeof(int));
    
            var price_child_acParameter = price_child_ac.HasValue ?
                new ObjectParameter("price_child_ac", price_child_ac) :
                new ObjectParameter("price_child_ac", typeof(int));
    
            var price_child_nonacParameter = price_child_nonac.HasValue ?
                new ObjectParameter("price_child_nonac", price_child_nonac) :
                new ObjectParameter("price_child_nonac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateHotel", hotel_idParameter, nameParameter, hotel_descriptionParameter, pinParameter, stateParameter, cityParameter, manager_idParameter, ac_roomParameter, non_ac_roomParameter, price_adult_acParameter, price_adult_nonacParameter, price_child_acParameter, price_child_nonacParameter);
        }
    
        public virtual int UpdateManagerDetails(string manager_id, string name, string password, Nullable<long> m_contact, string m_email)
        {
            var manager_idParameter = manager_id != null ?
                new ObjectParameter("manager_id", manager_id) :
                new ObjectParameter("manager_id", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var m_contactParameter = m_contact.HasValue ?
                new ObjectParameter("m_contact", m_contact) :
                new ObjectParameter("m_contact", typeof(long));
    
            var m_emailParameter = m_email != null ?
                new ObjectParameter("m_email", m_email) :
                new ObjectParameter("m_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateManagerDetails", manager_idParameter, nameParameter, passwordParameter, m_contactParameter, m_emailParameter);
        }
    }
}
