//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public string id { get; set; }
        public string Hotel_id { get; set; }
        public string customer_Id { get; set; }
        public string booking_name { get; set; }
        public int total_Cost { get; set; }
        public int card_number { get; set; }
        public string card_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Card_details Card_details { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
